# Generated by Django 5.2.5 on 2025-08-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact', models.CharField(max_length=20)),
                ('hallticket', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=20)),
            ],
        ),
    ]
