# Generated by Django 5.2.5 on 2025-08-29 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Pending...', 'Pending...'), ('Approved', 'Approved'), ('Canceled', 'Canceled')], default='Pending', max_length=20),
        ),
    ]
