# Generated by Django 5.2.5 on 2025-09-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='text',
            field=models.CharField(max_length=1000),
        ),
    ]
