# Generated by Django 5.2.5 on 2025-09-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_about_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='message',
            field=models.CharField(max_length=200),
        ),
    ]
