# Generated by Django 5.2.5 on 2025-09-02 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_about_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='message',
            new_name='BLOB',
        ),
    ]
