# Generated by Django 5.2.5 on 2025-09-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_rename_message_about_blob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='BLOB',
        ),
        migrations.AddField(
            model_name='about',
            name='texts',
            field=models.TextField(default=''),
        ),
    ]
