# Generated by Django 5.2.5 on 2025-09-02 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_aboutus_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='text',
            field=models.CharField(max_length=200),
        ),
    ]
