# Generated by Django 5.2.5 on 2025-09-02 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_aboutus_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutus',
            old_name='text',
            new_name='about',
        ),
    ]
