# Generated by Django 5.2.5 on 2025-09-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_rename_text_aboutus_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='about',
            field=models.TextField(),
        ),
    ]
