# Generated by Django 5.2.5 on 2025-09-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_aboutus_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='about',
            field=models.TextField(db_column='about_text'),
        ),
    ]
