# Generated by Django 5.2.5 on 2025-09-02 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_about_page'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutUs',
        ),
    ]
