# Generated by Django 5.2.5 on 2025-09-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_delete_aboutus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_page',
            name='about_pages',
            field=models.TextField(db_column='about_text'),
        ),
    ]
