# Generated by Django 5.2.5 on 2025-09-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_alter_about_page_about_pages'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('About_blogs', models.TextField(db_column='about_textss')),
            ],
        ),
        migrations.DeleteModel(
            name='About_page',
        ),
    ]
