# Generated by Django 5.2.5 on 2025-09-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_about_blog_delete_about_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_blog',
            name='About_blogs',
            field=models.TextField(),
        ),
    ]
