# Generated by Django 5.2.5 on 2025-09-12 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_alter_about_blog_about_blogs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About_blog',
        ),
    ]
