# Generated by Django 5.2.5 on 2025-09-13 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_doctor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='user',
        ),
    ]
